name: Test and build application

on:
  [push, pull_request]

jobs:
    tests:
        name: Cypress tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use node.js to run tests
              uses: actions/setup-node@v4
              with:
                node-version: 20.x

            - name: Install dependencies
              run: npm install

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                build: npm run build
                start: npm run dev
    